### ISSUE TITLE
Twitch Points Grabber is no longer working

### ISSUE THREAD

**Issue by shinji257** [Mene-hub/Twitch-Points-Grabber#1]
See subject.  It seems to have stopped working at some point.  Option no longer shows to toggle it on or off.

Using Firefox.

**Comment by Mene-hub** [comment]
Thanks for reporting the problem, sometimes Twitch changes the page a bit and i needs to update the extension. 
I'm working on it!

**Comment by Mene-hub** [comment]
I fixed the problem, you just have to wait for the change to be accepted by the stores

**Comment by Mene-hub** [comment]
It should be approved on firefox store, let me know if it works now!

**Comment by Mene-hub** [comment]
If it doesn't work,
try update the extension like this:
![image](https://user-images.githubusercontent.com/72011313/204331474-c6924f03-fe82-48de-afcf-626a322b76fb.png)

![image](https://user-images.githubusercontent.com/72011313/204331723-c320ecaf-6607-4039-afae-2ce9d96941d6.png)

**Comment by shinji257** [comment]
Sorry for the wait.  Looks like I got the update and it is showing the option now.
